version: '3.7'

services:
  app:
    container_name: app
    build:
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: "."
        target: "/app"
    depends_on:
      - db

  db:
    container_name: db
    build:
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_PASSWORD: password

volumes:
  db_data: