version: '3.7'

services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_PASSWORD: password

volumes:
  db_data: